name: Rust Component Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: mqtt-coder test
      run: cargo test --verbose
      working-directory: mqtt_coder
    - name: lib test
      run: cargo test --verbose
    - name: Install uv
      uses: astral-sh/setup-uv@v5
    - name: Install the project
      run: uv sync --locked --all-extras --dev && uv install pytest
      working-directory: interoperability_pytest
    - name: broker test
      run: uv run pytest
      
